services:
  - type: web
    name: car-rental-pro
    runtime: docker
    plan: free # or 'starter' if memory is an issue
    region: ohio
    envVars:
      - key: PORT
        value: 8080
      - key: PYTHON_VERSION
        value: 3.9
    healthCheckPath: /
